accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('signout/', views.signout, name='signout'),
    path('your-listings/', views.user_listings, name='user_listings'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordResetCompleteView .as_view(), name='password_change_done'),
]

home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.index, name='index'),
    path('browse/', views.browse_rooms, name='browse'),
    path('r/<int:room_id>/', views.detail, name='detail'),
    path('r/create', views.create, name='create'),
    path('search/', views.search, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roommate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    major = models.CharField(max_length=20)
    year = models.PositiveSmallIntegerField()
    gender_options = (('m', 'male'), 
                        ('f', 'female'),
                        ('o', 'other'))
    gender = models.CharField(choices=gender_options, max_length=6)
    
    def __str__(self):
        return self.user.username

home/models.py
from django.db import models

class Room(models.Model):
    """model for each room listing"""
    # add roommate preferences in the future
    host_name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    property_name = models.CharField(max_length=30, default="")
    description = models.TextField(default="", blank=True)
    cost = models.PositiveIntegerField(default=0)
    visits = models.PositiveIntegerField(default=0)
    property_type_options = (('a', 'apartment'),
                                ('c', 'condo'),
                                ('t', 'townhouse'),
                                ('h', 'house'))
    property_type = models.CharField(choices=property_type_options, max_length=10)
    number_of_rooms = models.PositiveSmallIntegerField()
    garages = models.PositiveSmallIntegerField()
    creator_id = models.PositiveIntegerField()
    creator_email = models.CharField(max_length=50)
    creator_phone = models.CharField(max_length=10, default="", blank=True)
    creator_gender = models.CharField(max_length=10)
    creator_major = models.CharField(max_length=20)
    creator_year = models.PositiveSmallIntegerField()
    last_updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.property_name

class RoomImage(models.Model):
    """child model of room model (many to one relationship)"""
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    image = models.ImageField()

accounts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            return user.save()

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

accounts/views.py
from .forms import UserRegistrationForm, LoginForm
from .models import Profile
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from home.models import Room

def signup(request):
    if request.method == 'POST':
        uf = UserRegistrationForm(request.POST)
        if uf.is_valid():
            user = uf.save()
            # sign the user in to their new account
            user = authenticate(username=uf.cleaned_data['username'],
                                password=uf.cleaned_data['password1'],)
            if user is not None:
                login(request, user)
                userprofile = Profile(user=user, year=1)
                userprofile.save()
                return redirect('edit_profile')
    else:
        uf = UserRegistrationForm()
    return render(request, 'signup.html', {'userform': uf})

def edit_profile(request):
    if request.method == 'POST':
        user = request.user
        profile = Profile.objects.get(user=user)
        profile.major = request.POST['major']
        profile.year = request.POST['year']
        profile.gender = request.POST['gender']
        profile.save()
        return render(request, 'signup_success.html')
    user = request.user
    profile = Profile.objects.get(user=user)
    return render(request, 'edit_profile.html', {'profile': profile})


def signin(request):
    if request.method == 'POST':
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():
            cd = loginForm.cleaned_data
            user = authenticate(username=cd['username'], 
                                password=cd['password'])
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                return render(request, 'signin.html', {'loginForm': loginForm,
                                                        'error_message': 'Your username and password did not match our records'})
    else:
        loginForm = LoginForm(request.POST)
    return render(request, 'signin.html', {'loginForm': loginForm})

def signout(request):
    logout(request)
    return redirect('index')

def user_listings(request):
    user_listings = []
    all_rooms = Room.objects.all()
    for room in all_rooms:
        if request.user.pk == room.creator_id:
            user_listings.append(room)
    return render(request, 'accounts/your_listings.html', {'user_listings': user_listings})

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block body %}
<form method='post' action="{% url 'edit_profile' %}">
    {% csrf_token %}
    <h1>Edit Profile</h1>
    <div class="w-100" style="height:50px;"></div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <h3>Your Account</h3>
            <div class="form-row">
                <div class="form-group col-md-10">
                    <label for="fName">First Name</label>
                    <input type="text" name="fName" value="{{user.first_name}}" id="fName" class="form-control" placeholder="Enter First Name" disabled>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-10">
                    <label for="lName">Last Name</label>
                    <input type="text" name="lName" value="{{user.last_name}}" id="lName" class="form-control" placeholder="Enter Last Name" disabled> 
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-10">
                    <label for="email">Email</label>
                    <input type="text" name="email" value="{{user.email}}" id="email" class="form-control" placeholder="Enter Email" disabled>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <h3>Your Profile</h3>
            <div class="form-row">
                <div class="form-group col-md-10">
                    <label for="majorInput">Major</label>
                    <input type="text" name="major" value="{{profile.major}}" id="majorInput" class="form-control" placeholder="Enter Major">
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-5">
                    <label for="exampleFormControlSelect1">Year</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="year">
                    <option {% if profile.year == 1 %}selected{% endif %} value="1">1</option>
                    <option {% if profile.year == 2 %}selected{% endif %} value="2">2</option>
                    <option {% if profile.year == 3 %}selected{% endif %} value="3">3</option>
                    <option {% if profile.year == 4 %}selected{% endif %} value="4">4+</option>
                    </select>
                </div>
                <div class="form-group col-md-5">
                    <label for="genderSelect">Gender</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="gender">
                        <option {% if profile.gender == 'm' %}selected{% endif %} value="m">Male</option>
                        <option {% if profile.gender == 'f' %}selected{% endif %} value="f">Female</option>
                        <option {% if profile.gender == 'o' %}selected{% endif %} value="o">Other</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <br>
    <button class="btn btn-lg btn-danger" type="submit">Save Profile</button>
</form>
{% endblock %}

accounts/templates/accounts/signin.html
{% extends 'base.html' %}

{% block body %}
<form method="post" action="{% url 'signin' %}">
    <h2>Sign In</h2>
    {% csrf_token %}
    {% if error_message %}
    <div class="alert alert-danger" role="alert">
        {{ error_message }}
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-4 col-sm-12">
            <div class="form-group">
                <div class="form-group">
                    <label for="usernameInput">Username</label>
                    <input type="text" class="form-control" id="usernameInput" aria-describedby="usernameHelp" placeholder="Username" name="username">
                </div>
                <div class="form-group">
                    <label for="passwordInput">Password</label>
                    <input type="password" class="form-control" id="passwordInput" placeholder="Password" name="password">
                </div>
            </div>
        </div>
    </div>
    <br>
    <button class="btn btn-lg btn-size btn-danger" type="submit">Sign In</button>
</form>
<br>
<a href="{% url 'signup' %}"><button class="btn btn-lg btn-size btn-light">Sign Up</button></a>
{% endblock %}

accounts/templates/accounts/signout_success.html
{% extends 'base.html' %}

{% block body %}
    <h1>Successfully signed out!</h1>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block body %}
  <h2>Sign Up</h2>
  <form method="post" action="{% url 'signup' %}">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="usernameInput">Username</label>
        <input type="text" name="username" class="form-control" placeholder="Username">  
      </div>
      <div class="form-group col-md-6">
        <label for="exampleInputEmail1">Email Address</label>
        <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Email">  
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="firstnameInput">First Name</label>
        <input type="text" name="first_name" class="form-control" placeholder="First Name">  
      </div>
      <div class="form-group col-md-6">
        <label for="lastnameInput">Last Name</label>
        <input type="text" name="last_name" class="form-control" placeholder="Last Name">
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="passwordInput">Password</label>
        <input type="password" name="password1" class="form-control" id="inputPassword5" placeholder="Password">  
      </div>
      <div class="form-group col-md-6">
        <label for="passwordconfirmationInput">Password Confirmation</label>
        <input type="password" name="password2" class="form-control" id="inputPassword6" placeholder="Confirm Password">
      </div>
    </div>
    <small id="password Help Block" class="form-text text-muted">
      Your password shouldn't be too similar to your other personal information,
      must contain at least 8 characters, shouldn't be a commonly used password,
      and shouldn't be entirely numeric.
    </small>
    <br>

    <button class="btn btn-size btn-danger btn-lg" type="submit">Sign Up</button>
    </form>
    
{% endblock %}

accounts/templates/accounts/signup_success.html
{% extends 'base.html' %}

{% block body %}
<div class="w-100" style="height:100px;"></div>
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Success!</h4>
  <p>Great job! you have finally made an account, now it's time to get started on creating a listing. Have Fun!</p>
  <hr>
  <p class="mb-0">If you have issues with your account information, you can always go back to edit profile and make the changes needed</p>
</div>
<a href="{% url 'index' %}"><button type="button" class="btn btn-danger">Home</button></a>
<a href="{% url 'search' %}"><button type="button" class="btn btn-danger">Browse Listings</button></a>
{% endblock %}

accounts/templates/accounts/your_listings.html
{% extends 'base.html' %}

{% block body %}
<div class="list-group list-group-flush"></div>
{% for room in user_listings %}
   <div class="list-group-item">
      <div class="row">
        <div class="col-12 col-md-2">
          <a href="{% url 'detail' room.id %}">
              <div class="img-thumbnail">
                <img src="{{ room.roomimage_set.all.0.image.url }}" alt="pic" >
              </div>
          </a>
        </div>

        <div class="pl-3 col-12 col-md-10">
           <a href="{% url 'detail' room.id %}"><h4 class="card-title m-1" >{{ room.property_name }}</h4></a>
           <p class="m-1">{{ room.address}}</p>
           <p class="m-1">${{ room.cost}}</p>
           <p class="m-1">{{ room.number_of_rooms}} Room(s)</p>
        </div>
      </div>
      <p class="text-muted m-0 pt-2">Last Updated: {{room.last_updated.date}}</p>
    </div>
{% endfor %}
</div>
{% endblock %}